### ISSUE TITLE
Image missing in plugin action links

### ISSUE THREAD

**Issue by xxsimoxx** [azurecurve/azrcrv-to-twitter#1]
![image](https://user-images.githubusercontent.com/29772709/114396140-7e88d700-9b9d-11eb-82a4-7a74af1616cc.png)

.../plugins/azrcrv-to-twitter/pluginmenu/images/Favicon-16x16.png is not in the folder.

**Comment by azurecurve** [comment]
v1.16.1 fixes the issue.
